name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]  # Triggers on pushes to 'main' branch
  workflow_dispatch:  # Allows manual trigger from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Move to the website directory
      - name: Change directory to website
        run: cd website

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"  # Or your preferred Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./website  # Ensure we run this inside the 'website' directory

      # Build Next.js app
      - name: Build Next.js app
        run: npm run build
        working-directory: ./website  # Run build inside 'website'

      # Export static files
      - name: Export static files
        run: npm run export
        working-directory: ./website  # Run export inside 'website'

      # Upload artifact for GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/out  # 'out' folder generated by Next.js export

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: out  # This is the folder where static files are located
